/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CreateUserRequest from './model/CreateUserRequest';
import CreateUserSuccess from './model/CreateUserSuccess';
import HeartbeatController200Response from './model/HeartbeatController200Response';
import HeartbeatResponse from './model/HeartbeatResponse';
import LoginRequest from './model/LoginRequest';
import LoginSuccess from './model/LoginSuccess';
import CreateApi from './api/CreateApi';
import DefaultApi from './api/DefaultApi';
import LoginApi from './api/LoginApi';


/**
* MultiTool.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MultiTool = require('index'); // See note below*.
* var xxxSvc = new MultiTool.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MultiTool.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MultiTool.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MultiTool.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreateUserRequest model constructor.
     * @property {module:model/CreateUserRequest}
     */
    CreateUserRequest,

    /**
     * The CreateUserSuccess model constructor.
     * @property {module:model/CreateUserSuccess}
     */
    CreateUserSuccess,

    /**
     * The HeartbeatController200Response model constructor.
     * @property {module:model/HeartbeatController200Response}
     */
    HeartbeatController200Response,

    /**
     * The HeartbeatResponse model constructor.
     * @property {module:model/HeartbeatResponse}
     */
    HeartbeatResponse,

    /**
     * The LoginRequest model constructor.
     * @property {module:model/LoginRequest}
     */
    LoginRequest,

    /**
     * The LoginSuccess model constructor.
     * @property {module:model/LoginSuccess}
     */
    LoginSuccess,

    /**
    * The CreateApi service constructor.
    * @property {module:api/CreateApi}
    */
    CreateApi,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The LoginApi service constructor.
    * @property {module:api/LoginApi}
    */
    LoginApi
};
