/**
 * MultiTool
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ApplicationConfig from './model/ApplicationConfig';
import ApplicationConfigOneOf from './model/ApplicationConfigOneOf';
import ApplicationDetails from './model/ApplicationDetails';
import ApplicationSummary from './model/ApplicationSummary';
import ApplicationType from './model/ApplicationType';
import AwsConfig from './model/AwsConfig';
import AwsIngressConfig from './model/AwsIngressConfig';
import AwsIngressConfigOneOf from './model/AwsIngressConfigOneOf';
import AwsIngressConfigOneOfRestApiGatewayConfig from './model/AwsIngressConfigOneOfRestApiGatewayConfig';
import AwsMonitorConfig from './model/AwsMonitorConfig';
import AwsPlatformConfig from './model/AwsPlatformConfig';
import AwsPlatformConfigOneOf from './model/AwsPlatformConfigOneOf';
import AwsPlatformConfigOneOfLambda from './model/AwsPlatformConfigOneOfLambda';
import CreateApplicationRequest from './model/CreateApplicationRequest';
import CreateApplicationSuccess from './model/CreateApplicationSuccess';
import CreateUserRequest from './model/CreateUserRequest';
import CreateUserSuccess from './model/CreateUserSuccess';
import CreateWorkspaceRequest from './model/CreateWorkspaceRequest';
import CreateWorkspaceSuccess from './model/CreateWorkspaceSuccess';
import ErrorResponse from './model/ErrorResponse';
import HeartbeatController200Response from './model/HeartbeatController200Response';
import ListApplicationsSuccess from './model/ListApplicationsSuccess';
import ListWorkspaceSuccess from './model/ListWorkspaceSuccess';
import LoginRequest from './model/LoginRequest';
import LoginSuccess from './model/LoginSuccess';
import UpdateWorkspaceRequest from './model/UpdateWorkspaceRequest';
import WebServiceConfig from './model/WebServiceConfig';
import WebServiceConfigOneOf from './model/WebServiceConfigOneOf';
import WorkspaceDetails from './model/WorkspaceDetails';
import WorkspaceSummary from './model/WorkspaceSummary';
import ApplicationsApi from './api/ApplicationsApi';
import HeartbeatApi from './api/HeartbeatApi';
import UsersApi from './api/UsersApi';
import WorkspacesApi from './api/WorkspacesApi';


/**
* MultiTool backend API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MultiTool = require('index'); // See note below*.
* var xxxSvc = new MultiTool.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MultiTool.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MultiTool.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MultiTool.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApplicationConfig model constructor.
     * @property {module:model/ApplicationConfig}
     */
    ApplicationConfig,

    /**
     * The ApplicationConfigOneOf model constructor.
     * @property {module:model/ApplicationConfigOneOf}
     */
    ApplicationConfigOneOf,

    /**
     * The ApplicationDetails model constructor.
     * @property {module:model/ApplicationDetails}
     */
    ApplicationDetails,

    /**
     * The ApplicationSummary model constructor.
     * @property {module:model/ApplicationSummary}
     */
    ApplicationSummary,

    /**
     * The ApplicationType model constructor.
     * @property {module:model/ApplicationType}
     */
    ApplicationType,

    /**
     * The AwsConfig model constructor.
     * @property {module:model/AwsConfig}
     */
    AwsConfig,

    /**
     * The AwsIngressConfig model constructor.
     * @property {module:model/AwsIngressConfig}
     */
    AwsIngressConfig,

    /**
     * The AwsIngressConfigOneOf model constructor.
     * @property {module:model/AwsIngressConfigOneOf}
     */
    AwsIngressConfigOneOf,

    /**
     * The AwsIngressConfigOneOfRestApiGatewayConfig model constructor.
     * @property {module:model/AwsIngressConfigOneOfRestApiGatewayConfig}
     */
    AwsIngressConfigOneOfRestApiGatewayConfig,

    /**
     * The AwsMonitorConfig model constructor.
     * @property {module:model/AwsMonitorConfig}
     */
    AwsMonitorConfig,

    /**
     * The AwsPlatformConfig model constructor.
     * @property {module:model/AwsPlatformConfig}
     */
    AwsPlatformConfig,

    /**
     * The AwsPlatformConfigOneOf model constructor.
     * @property {module:model/AwsPlatformConfigOneOf}
     */
    AwsPlatformConfigOneOf,

    /**
     * The AwsPlatformConfigOneOfLambda model constructor.
     * @property {module:model/AwsPlatformConfigOneOfLambda}
     */
    AwsPlatformConfigOneOfLambda,

    /**
     * The CreateApplicationRequest model constructor.
     * @property {module:model/CreateApplicationRequest}
     */
    CreateApplicationRequest,

    /**
     * The CreateApplicationSuccess model constructor.
     * @property {module:model/CreateApplicationSuccess}
     */
    CreateApplicationSuccess,

    /**
     * The CreateUserRequest model constructor.
     * @property {module:model/CreateUserRequest}
     */
    CreateUserRequest,

    /**
     * The CreateUserSuccess model constructor.
     * @property {module:model/CreateUserSuccess}
     */
    CreateUserSuccess,

    /**
     * The CreateWorkspaceRequest model constructor.
     * @property {module:model/CreateWorkspaceRequest}
     */
    CreateWorkspaceRequest,

    /**
     * The CreateWorkspaceSuccess model constructor.
     * @property {module:model/CreateWorkspaceSuccess}
     */
    CreateWorkspaceSuccess,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The HeartbeatController200Response model constructor.
     * @property {module:model/HeartbeatController200Response}
     */
    HeartbeatController200Response,

    /**
     * The ListApplicationsSuccess model constructor.
     * @property {module:model/ListApplicationsSuccess}
     */
    ListApplicationsSuccess,

    /**
     * The ListWorkspaceSuccess model constructor.
     * @property {module:model/ListWorkspaceSuccess}
     */
    ListWorkspaceSuccess,

    /**
     * The LoginRequest model constructor.
     * @property {module:model/LoginRequest}
     */
    LoginRequest,

    /**
     * The LoginSuccess model constructor.
     * @property {module:model/LoginSuccess}
     */
    LoginSuccess,

    /**
     * The UpdateWorkspaceRequest model constructor.
     * @property {module:model/UpdateWorkspaceRequest}
     */
    UpdateWorkspaceRequest,

    /**
     * The WebServiceConfig model constructor.
     * @property {module:model/WebServiceConfig}
     */
    WebServiceConfig,

    /**
     * The WebServiceConfigOneOf model constructor.
     * @property {module:model/WebServiceConfigOneOf}
     */
    WebServiceConfigOneOf,

    /**
     * The WorkspaceDetails model constructor.
     * @property {module:model/WorkspaceDetails}
     */
    WorkspaceDetails,

    /**
     * The WorkspaceSummary model constructor.
     * @property {module:model/WorkspaceSummary}
     */
    WorkspaceSummary,

    /**
    * The ApplicationsApi service constructor.
    * @property {module:api/ApplicationsApi}
    */
    ApplicationsApi,

    /**
    * The HeartbeatApi service constructor.
    * @property {module:api/HeartbeatApi}
    */
    HeartbeatApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi,

    /**
    * The WorkspacesApi service constructor.
    * @property {module:api/WorkspacesApi}
    */
    WorkspacesApi
};
