/**
 * MultiTool
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApplicationDetails from '../model/ApplicationDetails';
import CreateApplicationRequest from '../model/CreateApplicationRequest';
import CreateApplicationSuccess from '../model/CreateApplicationSuccess';
import ErrorResponse from '../model/ErrorResponse';
import ListApplicationsSuccess from '../model/ListApplicationsSuccess';

/**
* Applications service.
* @module api/ApplicationsApi
* @version 0.1.0
*/
export default class ApplicationsApi {

    /**
    * Constructs a new ApplicationsApi. 
    * @alias module:api/ApplicationsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {module:model/CreateApplicationRequest} createApplicationRequest 
     * @param {String} workspaceId The workspace's id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CreateApplicationSuccess} and HTTP response
     */
    createApplicationWithHttpInfo(createApplicationRequest, workspaceId) {
      let postBody = createApplicationRequest;
      // verify the required parameter 'createApplicationRequest' is set
      if (createApplicationRequest === undefined || createApplicationRequest === null) {
        throw new Error("Missing the required parameter 'createApplicationRequest' when calling createApplication");
      }
      // verify the required parameter 'workspaceId' is set
      if (workspaceId === undefined || workspaceId === null) {
        throw new Error("Missing the required parameter 'workspaceId' when calling createApplication");
      }

      let pathParams = {
        'workspace_id': workspaceId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_auth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateApplicationSuccess;
      return this.apiClient.callApi(
        '/api/v1/workspaces/{workspace_id}/applications', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {module:model/CreateApplicationRequest} createApplicationRequest 
     * @param {String} workspaceId The workspace's id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CreateApplicationSuccess}
     */
    createApplication(createApplicationRequest, workspaceId) {
      return this.createApplicationWithHttpInfo(createApplicationRequest, workspaceId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} workspaceId The workspace's id
     * @param {String} applicationId The application's id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deleteApplicationWithHttpInfo(workspaceId, applicationId) {
      let postBody = null;
      // verify the required parameter 'workspaceId' is set
      if (workspaceId === undefined || workspaceId === null) {
        throw new Error("Missing the required parameter 'workspaceId' when calling deleteApplication");
      }
      // verify the required parameter 'applicationId' is set
      if (applicationId === undefined || applicationId === null) {
        throw new Error("Missing the required parameter 'applicationId' when calling deleteApplication");
      }

      let pathParams = {
        'workspace_id': workspaceId,
        'application_id': applicationId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/workspaces/{workspace_id}/applications/{application_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} workspaceId The workspace's id
     * @param {String} applicationId The application's id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deleteApplication(workspaceId, applicationId) {
      return this.deleteApplicationWithHttpInfo(workspaceId, applicationId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} workspaceId The workspace's id
     * @param {String} applicationId The application's id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ApplicationDetails} and HTTP response
     */
    getApplicationWithHttpInfo(workspaceId, applicationId) {
      let postBody = null;
      // verify the required parameter 'workspaceId' is set
      if (workspaceId === undefined || workspaceId === null) {
        throw new Error("Missing the required parameter 'workspaceId' when calling getApplication");
      }
      // verify the required parameter 'applicationId' is set
      if (applicationId === undefined || applicationId === null) {
        throw new Error("Missing the required parameter 'applicationId' when calling getApplication");
      }

      let pathParams = {
        'workspace_id': workspaceId,
        'application_id': applicationId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ApplicationDetails;
      return this.apiClient.callApi(
        '/api/v1/workspaces/{workspace_id}/applications/{application_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} workspaceId The workspace's id
     * @param {String} applicationId The application's id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ApplicationDetails}
     */
    getApplication(workspaceId, applicationId) {
      return this.getApplicationWithHttpInfo(workspaceId, applicationId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} workspaceId The workspace's id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListApplicationsSuccess} and HTTP response
     */
    listApplicationsWithHttpInfo(workspaceId) {
      let postBody = null;
      // verify the required parameter 'workspaceId' is set
      if (workspaceId === undefined || workspaceId === null) {
        throw new Error("Missing the required parameter 'workspaceId' when calling listApplications");
      }

      let pathParams = {
        'workspace_id': workspaceId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListApplicationsSuccess;
      return this.apiClient.callApi(
        '/api/v1/workspaces/{workspace_id}/applications', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} workspaceId The workspace's id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListApplicationsSuccess}
     */
    listApplications(workspaceId) {
      return this.listApplicationsWithHttpInfo(workspaceId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
