/**
 * MultiTool
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateWorkspaceRequest from '../model/CreateWorkspaceRequest';
import CreateWorkspaceSuccess from '../model/CreateWorkspaceSuccess';
import ListWorkspaceSuccess from '../model/ListWorkspaceSuccess';
import UpdateWorkspaceRequest from '../model/UpdateWorkspaceRequest';
import WorkspaceDetails from '../model/WorkspaceDetails';

/**
* Workspaces service.
* @module api/WorkspacesApi
* @version 0.1.0
*/
export default class WorkspacesApi {

    /**
    * Constructs a new WorkspacesApi. 
    * @alias module:api/WorkspacesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {module:model/CreateWorkspaceRequest} createWorkspaceRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CreateWorkspaceSuccess} and HTTP response
     */
    createWorkspaceWithHttpInfo(createWorkspaceRequest) {
      let postBody = createWorkspaceRequest;
      // verify the required parameter 'createWorkspaceRequest' is set
      if (createWorkspaceRequest === undefined || createWorkspaceRequest === null) {
        throw new Error("Missing the required parameter 'createWorkspaceRequest' when calling createWorkspace");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_auth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateWorkspaceSuccess;
      return this.apiClient.callApi(
        '/api/v1/workspaces', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {module:model/CreateWorkspaceRequest} createWorkspaceRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CreateWorkspaceSuccess}
     */
    createWorkspace(createWorkspaceRequest) {
      return this.createWorkspaceWithHttpInfo(createWorkspaceRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Object} opts Optional parameters
     * @param {String} [displayName] Only return workspaces with this name.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListWorkspaceSuccess} and HTTP response
     */
    listWorkspacesWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'display_name': opts['displayName']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListWorkspaceSuccess;
      return this.apiClient.callApi(
        '/api/v1/workspaces', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.displayName Only return workspaces with this name.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListWorkspaceSuccess}
     */
    listWorkspaces(opts) {
      return this.listWorkspacesWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} id The workspace's id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/WorkspaceDetails} and HTTP response
     */
    readWorkspaceWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling readWorkspace");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = WorkspaceDetails;
      return this.apiClient.callApi(
        '/api/v1/workspaces/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} id The workspace's id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/WorkspaceDetails}
     */
    readWorkspace(id) {
      return this.readWorkspaceWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {module:model/UpdateWorkspaceRequest} updateWorkspaceRequest 
     * @param {String} id The workspace's id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/WorkspaceDetails} and HTTP response
     */
    updateWorkspaceWithHttpInfo(updateWorkspaceRequest, id) {
      let postBody = updateWorkspaceRequest;
      // verify the required parameter 'updateWorkspaceRequest' is set
      if (updateWorkspaceRequest === undefined || updateWorkspaceRequest === null) {
        throw new Error("Missing the required parameter 'updateWorkspaceRequest' when calling updateWorkspace");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateWorkspace");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_auth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = WorkspaceDetails;
      return this.apiClient.callApi(
        '/api/v1/workspaces/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {module:model/UpdateWorkspaceRequest} updateWorkspaceRequest 
     * @param {String} id The workspace's id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/WorkspaceDetails}
     */
    updateWorkspace(updateWorkspaceRequest, id) {
      return this.updateWorkspaceWithHttpInfo(updateWorkspaceRequest, id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
