[config]
default_to_workspace = false

[env]
CARGO_MAKE_COVERAGE_PROVIDER = "llvm-cov"
CARGO_MAKE_RUN_CODECOV = true
CARGO_NO_DEFAULT_FEATURES = "--no-default-features"
CARGO_MAKE_CARGO_BUILD_TEST_FLAGS = ""

[tasks.dev-test-flow]
dependencies = [
  "pre-build",
  "format-flow",
  "clippy-flow",
  "build",
  "post-build",
  "pre-docs",
  "docs",
  "post-docs",
  "test-flow",
]

[tasks.pre-build]
dependencies = [
  "sort-ci",
  "format-toml-conditioned-flow",
]

[tasks.ci-flow]
dependencies = [
  "pre-ci-flow",
  "print-env-flow",
  "pre-build",
  "check-format-flow",
  "clippy-flow",
  "build",
  "post-build",
  "pre-docs",
  "docs",
  "post-docs",
  "test-flow",
  "coverage-flow",
  "post-ci-flow",
]

[tasks.fmt]
workspace = true
alias = "format"

[tasks.check-format]
workspace = true

[tasks.wc]
description = "Calculate the LoC in src. Require tokei to be installed."
category = "Development"
command = "tokei"
args = [ "." ]

[tasks.sort-ci]
description = "Assert that Cargo.toml is sorted. Requires cargo-sort to be installed."
category = "Development"
command = "cargo"
args = ["sort", "--check"]

[tasks.sort]
description = "Sort Cargo.toml. Requires cargo-sort to be installed."
category = "Development"
command = "cargo"
args = ["sort"]

[tasks.generate]
description = "Generate all clients"
dependencies = ["gen-js", "gen-rust"]

[tasks.gen]
alias = "generate"

[tasks.gen-js]
description = "Generate an JavaScript client."
script = [
'''
docker run --rm -v "$PWD:/local" \
  openapitools/openapi-generator-cli:v7.4.0 generate \
  --skip-validate-spec \
  -i /local/openapi.json \
  -g javascript \
  --additional-properties prependFormOrBodyParameters=true \
  --additional-properties usePromises=true \
  -o /local/js
'''
]

[tasks.gen-rust]
description = "Generate a Rust client without validation."
script = [
'''
docker run --rm -v "$PWD:/local" \
  openapitools/openapi-generator-cli:v7.4.0 generate \
  -i /local/openapi.json \
  -g rust \
  -o /local/rust
'''
]
