/**
 * MultiTool
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MultiTool);
  }
}(this, function(expect, MultiTool) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MultiTool.AwsIngressConfigOneOfRestApiGatewayConfig();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AwsIngressConfigOneOfRestApiGatewayConfig', function() {
    it('should create an instance of AwsIngressConfigOneOfRestApiGatewayConfig', function() {
      // uncomment below and update the code to test AwsIngressConfigOneOfRestApiGatewayConfig
      //var instance = new MultiTool.AwsIngressConfigOneOfRestApiGatewayConfig();
      //expect(instance).to.be.a(MultiTool.AwsIngressConfigOneOfRestApiGatewayConfig);
    });

    it('should have the property gatewayName (base name: "gateway_name")', function() {
      // uncomment below and update the code to test the property gatewayName
      //var instance = new MultiTool.AwsIngressConfigOneOfRestApiGatewayConfig();
      //expect(instance).to.be();
    });

    it('should have the property resourceMethod (base name: "resource_method")', function() {
      // uncomment below and update the code to test the property resourceMethod
      //var instance = new MultiTool.AwsIngressConfigOneOfRestApiGatewayConfig();
      //expect(instance).to.be();
    });

    it('should have the property resourcePath (base name: "resource_path")', function() {
      // uncomment below and update the code to test the property resourcePath
      //var instance = new MultiTool.AwsIngressConfigOneOfRestApiGatewayConfig();
      //expect(instance).to.be();
    });

    it('should have the property stageName (base name: "stage_name")', function() {
      // uncomment below and update the code to test the property stageName
      //var instance = new MultiTool.AwsIngressConfigOneOfRestApiGatewayConfig();
      //expect(instance).to.be();
    });

  });

}));
