/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationConfigOneOf {
    #[serde(rename = "web_service")]
    pub web_service: Box<models::WebServiceConfig>,
}

impl ApplicationConfigOneOf {
    pub fn new(web_service: models::WebServiceConfig) -> ApplicationConfigOneOf {
        ApplicationConfigOneOf {
            web_service: Box::new(web_service),
        }
    }
}

