/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// ApplicationType : An identifier of what kind of application we're tracking.
/// An identifier of what kind of application we're tracking.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApplicationType {
    #[serde(rename = "web_service")]
    WebService,

}

impl ToString for ApplicationType {
    fn to_string(&self) -> String {
        match self {
            Self::WebService => String::from("web_service"),
        }
    }
}

impl Default for ApplicationType {
    fn default() -> ApplicationType {
        Self::WebService
    }
}

