/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApplicationConfig {
    ApplicationConfigOneOf(Box<models::ApplicationConfigOneOf>),
}

impl Default for ApplicationConfig {
    fn default() -> Self {
        Self::ApplicationConfigOneOf(Default::default())
    }
}

