/*
 * MultiTool
 *
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationDetails {
    #[serde(rename = "app_type")]
    pub app_type: models::ApplicationType,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "deployments")]
    pub deployments: Vec<serde_json::Value>,
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl ApplicationDetails {
    pub fn new(app_type: models::ApplicationType, created_at: String, deployments: Vec<serde_json::Value>, display_name: String, id: uuid::Uuid, updated_at: String) -> ApplicationDetails {
        ApplicationDetails {
            app_type,
            created_at,
            deployments,
            display_name,
            id,
            updated_at,
        }
    }
}

