/*
 * MultiTool
 *
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsIngressConfigOneOfRestApiGatewayConfig {
    #[serde(rename = "gateway_name")]
    pub gateway_name: String,
    #[serde(rename = "resource_method")]
    pub resource_method: String,
    #[serde(rename = "resource_path")]
    pub resource_path: String,
    #[serde(rename = "stage_name")]
    pub stage_name: String,
}

impl AwsIngressConfigOneOfRestApiGatewayConfig {
    pub fn new(gateway_name: String, resource_method: String, resource_path: String, stage_name: String) -> AwsIngressConfigOneOfRestApiGatewayConfig {
        AwsIngressConfigOneOfRestApiGatewayConfig {
            gateway_name,
            resource_method,
            resource_path,
            stage_name,
        }
    }
}

