/*
 * MultiTool
 *
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AwsIngressConfig {
    AwsIngressConfigOneOf(Box<models::AwsIngressConfigOneOf>),
}

impl Default for AwsIngressConfig {
    fn default() -> Self {
        Self::AwsIngressConfigOneOf(Default::default())
    }
}

