/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsConfig {
    #[serde(rename = "ingress")]
    pub ingress: Box<models::AwsIngressConfig>,
    #[serde(rename = "monitor")]
    pub monitor: models::AwsMonitorConfig,
    #[serde(rename = "platform")]
    pub platform: Box<models::AwsPlatformConfig>,
    #[serde(rename = "region")]
    pub region: String,
}

impl AwsConfig {
    pub fn new(ingress: models::AwsIngressConfig, monitor: models::AwsMonitorConfig, platform: models::AwsPlatformConfig, region: String) -> AwsConfig {
        AwsConfig {
            ingress: Box::new(ingress),
            monitor,
            platform: Box::new(platform),
            region,
        }
    }
}

