/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsPlatformConfigOneOf {
    #[serde(rename = "lambda")]
    pub lambda: Box<models::AwsPlatformConfigOneOfLambda>,
}

impl AwsPlatformConfigOneOf {
    pub fn new(lambda: models::AwsPlatformConfigOneOfLambda) -> AwsPlatformConfigOneOf {
        AwsPlatformConfigOneOf {
            lambda: Box::new(lambda),
        }
    }
}

