/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AwsPlatformConfig {
    AwsPlatformConfigOneOf(Box<models::AwsPlatformConfigOneOf>),
}

impl Default for AwsPlatformConfig {
    fn default() -> Self {
        Self::AwsPlatformConfigOneOf(Default::default())
    }
}

