/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AwsMonitorConfig {
    #[serde(rename = "cloudwatch_metrics")]
    CloudwatchMetrics,

}

impl ToString for AwsMonitorConfig {
    fn to_string(&self) -> String {
        match self {
            Self::CloudwatchMetrics => String::from("cloudwatch_metrics"),
        }
    }
}

impl Default for AwsMonitorConfig {
    fn default() -> AwsMonitorConfig {
        Self::CloudwatchMetrics
    }
}

