/*
 * MultiTool
 *
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsPlatformConfigOneOfLambda {
    #[serde(rename = "name")]
    pub name: String,
}

impl AwsPlatformConfigOneOfLambda {
    pub fn new(name: String) -> AwsPlatformConfigOneOfLambda {
        AwsPlatformConfigOneOfLambda {
            name,
        }
    }
}

