/*
 * MultiTool
 *
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsIngressConfigOneOf {
    #[serde(rename = "rest_api_gateway_config")]
    pub rest_api_gateway_config: Box<models::AwsIngressConfigOneOfRestApiGatewayConfig>,
}

impl AwsIngressConfigOneOf {
    pub fn new(rest_api_gateway_config: models::AwsIngressConfigOneOfRestApiGatewayConfig) -> AwsIngressConfigOneOf {
        AwsIngressConfigOneOf {
            rest_api_gateway_config: Box::new(rest_api_gateway_config),
        }
    }
}

