/*
 * MultiTool
 *
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// CreateUserFailureOneOfEmailAlreadyRegistered : When the email address is already associated with an account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserFailureOneOfEmailAlreadyRegistered {
    #[serde(rename = "email")]
    pub email: String,
}

impl CreateUserFailureOneOfEmailAlreadyRegistered {
    /// When the email address is already associated with an account.
    pub fn new(email: String) -> CreateUserFailureOneOfEmailAlreadyRegistered {
        CreateUserFailureOneOfEmailAlreadyRegistered {
            email,
        }
    }
}

