/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// CreateUserSuccess : Successful user creation response body
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserSuccess {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "expires_at")]
    pub expires_at: String,
    #[serde(rename = "jwt")]
    pub jwt: String,
}

impl CreateUserSuccess {
    /// Successful user creation response body
    pub fn new(created_at: String, email: String, expires_at: String, jwt: String) -> CreateUserSuccess {
        CreateUserSuccess {
            created_at,
            email,
            expires_at,
            jwt,
        }
    }
}

