/*
 * MultiTool
 *
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// CreateUserFailure : Failure to create a new users. Corresponds to POST /users/
/// Failure to create a new users. Corresponds to POST /users/
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateUserFailure {
    CreateUserFailureOneOf(Box<models::CreateUserFailureOneOf>),
    /// When the user's password is not strong enough.
    String(String),
    /// When the server encountered an internal error.
    String(String),
    CreateUserFailureOneOf1(Box<models::CreateUserFailureOneOf1>),
    /// When the user's password matches their account name or email.
    String(String),
}

impl Default for CreateUserFailure {
    fn default() -> Self {
        Self::CreateUserFailureOneOf(Default::default())
    }
}

