/*
 * MultiTool
 *
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// CreateUserFailureOneOf1 : When the user's email or account name are illegal.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserFailureOneOf1 {
    /// When the user's email or account name are illegal.
    #[serde(rename = "IllegalUserDetails")]
    pub illegal_user_details: String,
}

impl CreateUserFailureOneOf1 {
    /// When the user's email or account name are illegal.
    pub fn new(illegal_user_details: String) -> CreateUserFailureOneOf1 {
        CreateUserFailureOneOf1 {
            illegal_user_details,
        }
    }
}

