/*
 * MultiTool
 *
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// CreateUserRequest : Expected body of user endpoint requests
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserRequest {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "password")]
    pub password: String,
}

impl CreateUserRequest {
    /// Expected body of user endpoint requests
    pub fn new(email: String, password: String) -> CreateUserRequest {
        CreateUserRequest {
            email,
            password,
        }
    }
}

