/*
 * MultiTool
 *
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// CreateUserFailureOneOf : When the email address is already associated with an account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserFailureOneOf {
    #[serde(rename = "EmailAlreadyRegistered")]
    pub email_already_registered: Box<models::CreateUserFailureOneOfEmailAlreadyRegistered>,
}

impl CreateUserFailureOneOf {
    /// When the email address is already associated with an account.
    pub fn new(email_already_registered: models::CreateUserFailureOneOfEmailAlreadyRegistered) -> CreateUserFailureOneOf {
        CreateUserFailureOneOf {
            email_already_registered: Box::new(email_already_registered),
        }
    }
}

