/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApplicationRequest {
    #[serde(rename = "config")]
    pub config: Box<models::ApplicationConfig>,
    #[serde(rename = "display_name")]
    pub display_name: String,
}

impl CreateApplicationRequest {
    pub fn new(config: models::ApplicationConfig, display_name: String) -> CreateApplicationRequest {
        CreateApplicationRequest {
            config: Box::new(config),
            display_name,
        }
    }
}

