/*
 * MultiTool
 *
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWorkspaceRequest {
    #[serde(rename = "display_name")]
    pub display_name: String,
}

impl CreateWorkspaceRequest {
    pub fn new(display_name: String) -> CreateWorkspaceRequest {
        CreateWorkspaceRequest {
            display_name,
        }
    }
}

