/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApplicationSuccess {
    #[serde(rename = "application")]
    pub application: Box<models::ApplicationSummary>,
}

impl CreateApplicationSuccess {
    pub fn new(application: models::ApplicationSummary) -> CreateApplicationSuccess {
        CreateApplicationSuccess {
            application: Box::new(application),
        }
    }
}

