/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    #[serde(rename = "errors")]
    pub errors: Vec<String>,
}

impl ErrorResponse {
    pub fn new(errors: Vec<String>) -> ErrorResponse {
        ErrorResponse {
            errors,
        }
    }
}

