/*
 * MultiTool
 *
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// HeartbeatResponse : A Heartbeat response indicates the status of the server. In almost every conceivable circumstance, the response should be a success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HeartbeatResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
}

impl HeartbeatResponse {
    /// A Heartbeat response indicates the status of the server. In almost every conceivable circumstance, the response should be a success.
    pub fn new(ok: bool) -> HeartbeatResponse {
        HeartbeatResponse {
            ok,
        }
    }
}

