/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListWorkspaceSuccess {
    #[serde(rename = "workspaces")]
    pub workspaces: Vec<models::WorkspaceSummary>,
}

impl ListWorkspaceSuccess {
    pub fn new(workspaces: Vec<models::WorkspaceSummary>) -> ListWorkspaceSuccess {
        ListWorkspaceSuccess {
            workspaces,
        }
    }
}

