/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListApplicationsSuccess {
    #[serde(rename = "applications")]
    pub applications: Vec<models::ApplicationSummary>,
}

impl ListApplicationsSuccess {
    pub fn new(applications: Vec<models::ApplicationSummary>) -> ListApplicationsSuccess {
        ListApplicationsSuccess {
            applications,
        }
    }
}

