/*
 * MultiTool
 *
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// LoginSuccess : Successful login response payload
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginSuccess {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "jwt")]
    pub jwt: String,
}

impl LoginSuccess {
    /// Successful login response payload
    pub fn new(email: String, jwt: String) -> LoginSuccess {
        LoginSuccess {
            email,
            jwt,
        }
    }
}

