/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebServiceConfigOneOf {
    #[serde(rename = "aws")]
    pub aws: Box<models::AwsConfig>,
}

impl WebServiceConfigOneOf {
    pub fn new(aws: models::AwsConfig) -> WebServiceConfigOneOf {
        WebServiceConfigOneOf {
            aws: Box::new(aws),
        }
    }
}

