/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WebServiceConfig {
    WebServiceConfigOneOf(Box<models::WebServiceConfigOneOf>),
}

impl Default for WebServiceConfig {
    fn default() -> Self {
        Self::WebServiceConfigOneOf(Default::default())
    }
}

