/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceSummary {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
}

impl WorkspaceSummary {
    pub fn new(created_at: String, display_name: String, id: uuid::Uuid) -> WorkspaceSummary {
        WorkspaceSummary {
            created_at,
            display_name,
            id,
        }
    }
}

