/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// WorkspaceDetails : Details about a particular workspace.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceDetails {
    #[serde(rename = "applications")]
    pub applications: Vec<models::ApplicationSummary>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl WorkspaceDetails {
    /// Details about a particular workspace.
    pub fn new(applications: Vec<models::ApplicationSummary>, created_at: String, display_name: String, id: uuid::Uuid, updated_at: String) -> WorkspaceDetails {
        WorkspaceDetails {
            applications,
            created_at,
            display_name,
            id,
            updated_at,
        }
    }
}

