/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ApplicationType.
* @enum {}
* @readonly
*/
export default class ApplicationType {
    
        /**
         * value: "web_service"
         * @const
         */
        "web_service" = "web_service";

    

    /**
    * Returns a <code>ApplicationType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ApplicationType} The enum <code>ApplicationType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

