/**
 * MultiTool
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationType from './ApplicationType';

/**
 * The ApplicationSummary model module.
 * @module model/ApplicationSummary
 * @version 0.1.0
 */
class ApplicationSummary {
    /**
     * Constructs a new <code>ApplicationSummary</code>.
     * @alias module:model/ApplicationSummary
     * @param appType {module:model/ApplicationType} 
     * @param createdAt {String} 
     * @param displayName {String} 
     * @param id {String} 
     * @param updatedAt {String} 
     */
    constructor(appType, createdAt, displayName, id, updatedAt) { 
        
        ApplicationSummary.initialize(this, appType, createdAt, displayName, id, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, appType, createdAt, displayName, id, updatedAt) { 
        obj['app_type'] = appType;
        obj['created_at'] = createdAt;
        obj['display_name'] = displayName;
        obj['id'] = id;
        obj['updated_at'] = updatedAt;
    }

    /**
     * Constructs a <code>ApplicationSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationSummary} obj Optional instance to populate.
     * @return {module:model/ApplicationSummary} The populated <code>ApplicationSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationSummary();

            if (data.hasOwnProperty('app_type')) {
                obj['app_type'] = ApplicationType.constructFromObject(data['app_type']);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApplicationSummary</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApplicationSummary</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApplicationSummary.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }
        // ensure the json data is a string
        if (data['display_name'] && !(typeof data['display_name'] === 'string' || data['display_name'] instanceof String)) {
            throw new Error("Expected the field `display_name` to be a primitive type in the JSON string but got " + data['display_name']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['updated_at'] && !(typeof data['updated_at'] === 'string' || data['updated_at'] instanceof String)) {
            throw new Error("Expected the field `updated_at` to be a primitive type in the JSON string but got " + data['updated_at']);
        }

        return true;
    }


}

ApplicationSummary.RequiredProperties = ["app_type", "created_at", "display_name", "id", "updated_at"];

/**
 * @member {module:model/ApplicationType} app_type
 */
ApplicationSummary.prototype['app_type'] = undefined;

/**
 * @member {String} created_at
 */
ApplicationSummary.prototype['created_at'] = undefined;

/**
 * @member {String} display_name
 */
ApplicationSummary.prototype['display_name'] = undefined;

/**
 * @member {String} id
 */
ApplicationSummary.prototype['id'] = undefined;

/**
 * @member {String} updated_at
 */
ApplicationSummary.prototype['updated_at'] = undefined;






export default ApplicationSummary;

