/**
 * MultiTool
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WebServiceConfig from './WebServiceConfig';

/**
 * The ApplicationConfigOneOf model module.
 * @module model/ApplicationConfigOneOf
 * @version 0.1.0
 */
class ApplicationConfigOneOf {
    /**
     * Constructs a new <code>ApplicationConfigOneOf</code>.
     * @alias module:model/ApplicationConfigOneOf
     * @param webService {module:model/WebServiceConfig} 
     */
    constructor(webService) { 
        
        ApplicationConfigOneOf.initialize(this, webService);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, webService) { 
        obj['web_service'] = webService;
    }

    /**
     * Constructs a <code>ApplicationConfigOneOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationConfigOneOf} obj Optional instance to populate.
     * @return {module:model/ApplicationConfigOneOf} The populated <code>ApplicationConfigOneOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationConfigOneOf();

            if (data.hasOwnProperty('web_service')) {
                obj['web_service'] = WebServiceConfig.constructFromObject(data['web_service']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApplicationConfigOneOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApplicationConfigOneOf</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApplicationConfigOneOf.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `web_service`
        if (data['web_service']) { // data not null
          WebServiceConfig.validateJSON(data['web_service']);
        }

        return true;
    }


}

ApplicationConfigOneOf.RequiredProperties = ["web_service"];

/**
 * @member {module:model/WebServiceConfig} web_service
 */
ApplicationConfigOneOf.prototype['web_service'] = undefined;






export default ApplicationConfigOneOf;

