/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationConfigOneOf from './ApplicationConfigOneOf';
import WebServiceConfig from './WebServiceConfig';

/**
 * The ApplicationConfig model module.
 * @module model/ApplicationConfig
 * @version 0.1.0
 */
class ApplicationConfig {
    /**
     * Constructs a new <code>ApplicationConfig</code>.
     * @alias module:model/ApplicationConfig
     * @param {(module:model/ApplicationConfigOneOf)} instance The actual instance to initialize ApplicationConfig.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "ApplicationConfigOneOf") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                ApplicationConfigOneOf.validateJSON(instance); // throw an exception if no match
                // create ApplicationConfigOneOf from JS object
                this.actualInstance = ApplicationConfigOneOf.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into ApplicationConfigOneOf
            errorMessages.push("Failed to construct ApplicationConfigOneOf: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `ApplicationConfig` with oneOf schemas ApplicationConfigOneOf. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `ApplicationConfig` with oneOf schemas ApplicationConfigOneOf. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>ApplicationConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationConfig} obj Optional instance to populate.
     * @return {module:model/ApplicationConfig} The populated <code>ApplicationConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        return new ApplicationConfig(data);
    }

    /**
     * Gets the actual instance, which can be <code>ApplicationConfigOneOf</code>.
     * @return {(module:model/ApplicationConfigOneOf)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>ApplicationConfigOneOf</code>.
     * @param {(module:model/ApplicationConfigOneOf)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = ApplicationConfig.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of ApplicationConfig from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/ApplicationConfig} An instance of ApplicationConfig.
     */
    static fromJSON = function(json_string){
        return ApplicationConfig.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/WebServiceConfig} web_service
 */
ApplicationConfig.prototype['web_service'] = undefined;


ApplicationConfig.OneOf = ["ApplicationConfigOneOf"];

export default ApplicationConfig;

