/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AwsIngressConfig from './AwsIngressConfig';
import AwsMonitorConfig from './AwsMonitorConfig';
import AwsPlatformConfig from './AwsPlatformConfig';

/**
 * The AwsConfig model module.
 * @module model/AwsConfig
 * @version 0.1.0
 */
class AwsConfig {
    /**
     * Constructs a new <code>AwsConfig</code>.
     * @alias module:model/AwsConfig
     * @param ingress {module:model/AwsIngressConfig} 
     * @param monitor {module:model/AwsMonitorConfig} 
     * @param platform {module:model/AwsPlatformConfig} 
     * @param region {String} 
     */
    constructor(ingress, monitor, platform, region) { 
        
        AwsConfig.initialize(this, ingress, monitor, platform, region);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ingress, monitor, platform, region) { 
        obj['ingress'] = ingress;
        obj['monitor'] = monitor;
        obj['platform'] = platform;
        obj['region'] = region;
    }

    /**
     * Constructs a <code>AwsConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AwsConfig} obj Optional instance to populate.
     * @return {module:model/AwsConfig} The populated <code>AwsConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AwsConfig();

            if (data.hasOwnProperty('ingress')) {
                obj['ingress'] = AwsIngressConfig.constructFromObject(data['ingress']);
            }
            if (data.hasOwnProperty('monitor')) {
                obj['monitor'] = AwsMonitorConfig.constructFromObject(data['monitor']);
            }
            if (data.hasOwnProperty('platform')) {
                obj['platform'] = AwsPlatformConfig.constructFromObject(data['platform']);
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiClient.convertToType(data['region'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AwsConfig</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AwsConfig</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AwsConfig.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `ingress`
        if (data['ingress']) { // data not null
          AwsIngressConfig.validateJSON(data['ingress']);
        }
        // validate the optional field `platform`
        if (data['platform']) { // data not null
          AwsPlatformConfig.validateJSON(data['platform']);
        }
        // ensure the json data is a string
        if (data['region'] && !(typeof data['region'] === 'string' || data['region'] instanceof String)) {
            throw new Error("Expected the field `region` to be a primitive type in the JSON string but got " + data['region']);
        }

        return true;
    }


}

AwsConfig.RequiredProperties = ["ingress", "monitor", "platform", "region"];

/**
 * @member {module:model/AwsIngressConfig} ingress
 */
AwsConfig.prototype['ingress'] = undefined;

/**
 * @member {module:model/AwsMonitorConfig} monitor
 */
AwsConfig.prototype['monitor'] = undefined;

/**
 * @member {module:model/AwsPlatformConfig} platform
 */
AwsConfig.prototype['platform'] = undefined;

/**
 * @member {String} region
 */
AwsConfig.prototype['region'] = undefined;






export default AwsConfig;

