/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AwsIngressConfigOneOfRestApiGatewayConfig from './AwsIngressConfigOneOfRestApiGatewayConfig';

/**
 * The AwsIngressConfigOneOf model module.
 * @module model/AwsIngressConfigOneOf
 * @version 0.1.0
 */
class AwsIngressConfigOneOf {
    /**
     * Constructs a new <code>AwsIngressConfigOneOf</code>.
     * @alias module:model/AwsIngressConfigOneOf
     * @param restApiGatewayConfig {module:model/AwsIngressConfigOneOfRestApiGatewayConfig} 
     */
    constructor(restApiGatewayConfig) { 
        
        AwsIngressConfigOneOf.initialize(this, restApiGatewayConfig);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, restApiGatewayConfig) { 
        obj['rest_api_gateway_config'] = restApiGatewayConfig;
    }

    /**
     * Constructs a <code>AwsIngressConfigOneOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AwsIngressConfigOneOf} obj Optional instance to populate.
     * @return {module:model/AwsIngressConfigOneOf} The populated <code>AwsIngressConfigOneOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AwsIngressConfigOneOf();

            if (data.hasOwnProperty('rest_api_gateway_config')) {
                obj['rest_api_gateway_config'] = AwsIngressConfigOneOfRestApiGatewayConfig.constructFromObject(data['rest_api_gateway_config']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AwsIngressConfigOneOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AwsIngressConfigOneOf</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AwsIngressConfigOneOf.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `rest_api_gateway_config`
        if (data['rest_api_gateway_config']) { // data not null
          AwsIngressConfigOneOfRestApiGatewayConfig.validateJSON(data['rest_api_gateway_config']);
        }

        return true;
    }


}

AwsIngressConfigOneOf.RequiredProperties = ["rest_api_gateway_config"];

/**
 * @member {module:model/AwsIngressConfigOneOfRestApiGatewayConfig} rest_api_gateway_config
 */
AwsIngressConfigOneOf.prototype['rest_api_gateway_config'] = undefined;






export default AwsIngressConfigOneOf;

