/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AwsIngressConfigOneOf from './AwsIngressConfigOneOf';
import AwsIngressConfigOneOfRestApiGatewayConfig from './AwsIngressConfigOneOfRestApiGatewayConfig';

/**
 * The AwsIngressConfig model module.
 * @module model/AwsIngressConfig
 * @version 0.1.0
 */
class AwsIngressConfig {
    /**
     * Constructs a new <code>AwsIngressConfig</code>.
     * @alias module:model/AwsIngressConfig
     * @param {(module:model/AwsIngressConfigOneOf)} instance The actual instance to initialize AwsIngressConfig.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "AwsIngressConfigOneOf") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                AwsIngressConfigOneOf.validateJSON(instance); // throw an exception if no match
                // create AwsIngressConfigOneOf from JS object
                this.actualInstance = AwsIngressConfigOneOf.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into AwsIngressConfigOneOf
            errorMessages.push("Failed to construct AwsIngressConfigOneOf: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `AwsIngressConfig` with oneOf schemas AwsIngressConfigOneOf. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `AwsIngressConfig` with oneOf schemas AwsIngressConfigOneOf. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>AwsIngressConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AwsIngressConfig} obj Optional instance to populate.
     * @return {module:model/AwsIngressConfig} The populated <code>AwsIngressConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        return new AwsIngressConfig(data);
    }

    /**
     * Gets the actual instance, which can be <code>AwsIngressConfigOneOf</code>.
     * @return {(module:model/AwsIngressConfigOneOf)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>AwsIngressConfigOneOf</code>.
     * @param {(module:model/AwsIngressConfigOneOf)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = AwsIngressConfig.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of AwsIngressConfig from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/AwsIngressConfig} An instance of AwsIngressConfig.
     */
    static fromJSON = function(json_string){
        return AwsIngressConfig.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/AwsIngressConfigOneOfRestApiGatewayConfig} rest_api_gateway_config
 */
AwsIngressConfig.prototype['rest_api_gateway_config'] = undefined;


AwsIngressConfig.OneOf = ["AwsIngressConfigOneOf"];

export default AwsIngressConfig;

