/**
 * MultiTool
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AwsIngressConfigOneOfRestApiGatewayConfig model module.
 * @module model/AwsIngressConfigOneOfRestApiGatewayConfig
 * @version 0.1.0
 */
class AwsIngressConfigOneOfRestApiGatewayConfig {
    /**
     * Constructs a new <code>AwsIngressConfigOneOfRestApiGatewayConfig</code>.
     * @alias module:model/AwsIngressConfigOneOfRestApiGatewayConfig
     * @param gatewayName {String} 
     * @param resourceMethod {String} 
     * @param resourcePath {String} 
     * @param stageName {String} 
     */
    constructor(gatewayName, resourceMethod, resourcePath, stageName) { 
        
        AwsIngressConfigOneOfRestApiGatewayConfig.initialize(this, gatewayName, resourceMethod, resourcePath, stageName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, gatewayName, resourceMethod, resourcePath, stageName) { 
        obj['gateway_name'] = gatewayName;
        obj['resource_method'] = resourceMethod;
        obj['resource_path'] = resourcePath;
        obj['stage_name'] = stageName;
    }

    /**
     * Constructs a <code>AwsIngressConfigOneOfRestApiGatewayConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AwsIngressConfigOneOfRestApiGatewayConfig} obj Optional instance to populate.
     * @return {module:model/AwsIngressConfigOneOfRestApiGatewayConfig} The populated <code>AwsIngressConfigOneOfRestApiGatewayConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AwsIngressConfigOneOfRestApiGatewayConfig();

            if (data.hasOwnProperty('gateway_name')) {
                obj['gateway_name'] = ApiClient.convertToType(data['gateway_name'], 'String');
            }
            if (data.hasOwnProperty('resource_method')) {
                obj['resource_method'] = ApiClient.convertToType(data['resource_method'], 'String');
            }
            if (data.hasOwnProperty('resource_path')) {
                obj['resource_path'] = ApiClient.convertToType(data['resource_path'], 'String');
            }
            if (data.hasOwnProperty('stage_name')) {
                obj['stage_name'] = ApiClient.convertToType(data['stage_name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AwsIngressConfigOneOfRestApiGatewayConfig</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AwsIngressConfigOneOfRestApiGatewayConfig</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AwsIngressConfigOneOfRestApiGatewayConfig.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['gateway_name'] && !(typeof data['gateway_name'] === 'string' || data['gateway_name'] instanceof String)) {
            throw new Error("Expected the field `gateway_name` to be a primitive type in the JSON string but got " + data['gateway_name']);
        }
        // ensure the json data is a string
        if (data['resource_method'] && !(typeof data['resource_method'] === 'string' || data['resource_method'] instanceof String)) {
            throw new Error("Expected the field `resource_method` to be a primitive type in the JSON string but got " + data['resource_method']);
        }
        // ensure the json data is a string
        if (data['resource_path'] && !(typeof data['resource_path'] === 'string' || data['resource_path'] instanceof String)) {
            throw new Error("Expected the field `resource_path` to be a primitive type in the JSON string but got " + data['resource_path']);
        }
        // ensure the json data is a string
        if (data['stage_name'] && !(typeof data['stage_name'] === 'string' || data['stage_name'] instanceof String)) {
            throw new Error("Expected the field `stage_name` to be a primitive type in the JSON string but got " + data['stage_name']);
        }

        return true;
    }


}

AwsIngressConfigOneOfRestApiGatewayConfig.RequiredProperties = ["gateway_name", "resource_method", "resource_path", "stage_name"];

/**
 * @member {String} gateway_name
 */
AwsIngressConfigOneOfRestApiGatewayConfig.prototype['gateway_name'] = undefined;

/**
 * @member {String} resource_method
 */
AwsIngressConfigOneOfRestApiGatewayConfig.prototype['resource_method'] = undefined;

/**
 * @member {String} resource_path
 */
AwsIngressConfigOneOfRestApiGatewayConfig.prototype['resource_path'] = undefined;

/**
 * @member {String} stage_name
 */
AwsIngressConfigOneOfRestApiGatewayConfig.prototype['stage_name'] = undefined;






export default AwsIngressConfigOneOfRestApiGatewayConfig;

