/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AwsMonitorConfig.
* @enum {}
* @readonly
*/
export default class AwsMonitorConfig {
    
        /**
         * value: "cloudwatch_metrics"
         * @const
         */
        "cloudwatch_metrics" = "cloudwatch_metrics";

    

    /**
    * Returns a <code>AwsMonitorConfig</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AwsMonitorConfig} The enum <code>AwsMonitorConfig</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

