/**
 * MultiTool
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AwsPlatformConfigOneOf from './AwsPlatformConfigOneOf';
import AwsPlatformConfigOneOfLambda from './AwsPlatformConfigOneOfLambda';

/**
 * The AwsPlatformConfig model module.
 * @module model/AwsPlatformConfig
 * @version 0.1.0
 */
class AwsPlatformConfig {
    /**
     * Constructs a new <code>AwsPlatformConfig</code>.
     * @alias module:model/AwsPlatformConfig
     * @param {(module:model/AwsPlatformConfigOneOf)} instance The actual instance to initialize AwsPlatformConfig.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "AwsPlatformConfigOneOf") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                AwsPlatformConfigOneOf.validateJSON(instance); // throw an exception if no match
                // create AwsPlatformConfigOneOf from JS object
                this.actualInstance = AwsPlatformConfigOneOf.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into AwsPlatformConfigOneOf
            errorMessages.push("Failed to construct AwsPlatformConfigOneOf: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `AwsPlatformConfig` with oneOf schemas AwsPlatformConfigOneOf. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `AwsPlatformConfig` with oneOf schemas AwsPlatformConfigOneOf. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>AwsPlatformConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AwsPlatformConfig} obj Optional instance to populate.
     * @return {module:model/AwsPlatformConfig} The populated <code>AwsPlatformConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        return new AwsPlatformConfig(data);
    }

    /**
     * Gets the actual instance, which can be <code>AwsPlatformConfigOneOf</code>.
     * @return {(module:model/AwsPlatformConfigOneOf)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>AwsPlatformConfigOneOf</code>.
     * @param {(module:model/AwsPlatformConfigOneOf)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = AwsPlatformConfig.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of AwsPlatformConfig from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/AwsPlatformConfig} An instance of AwsPlatformConfig.
     */
    static fromJSON = function(json_string){
        return AwsPlatformConfig.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/AwsPlatformConfigOneOfLambda} lambda
 */
AwsPlatformConfig.prototype['lambda'] = undefined;


AwsPlatformConfig.OneOf = ["AwsPlatformConfigOneOf"];

export default AwsPlatformConfig;

