/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AwsPlatformConfigOneOfLambda from './AwsPlatformConfigOneOfLambda';

/**
 * The AwsPlatformConfigOneOf model module.
 * @module model/AwsPlatformConfigOneOf
 * @version 0.1.0
 */
class AwsPlatformConfigOneOf {
    /**
     * Constructs a new <code>AwsPlatformConfigOneOf</code>.
     * @alias module:model/AwsPlatformConfigOneOf
     * @param lambda {module:model/AwsPlatformConfigOneOfLambda} 
     */
    constructor(lambda) { 
        
        AwsPlatformConfigOneOf.initialize(this, lambda);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, lambda) { 
        obj['lambda'] = lambda;
    }

    /**
     * Constructs a <code>AwsPlatformConfigOneOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AwsPlatformConfigOneOf} obj Optional instance to populate.
     * @return {module:model/AwsPlatformConfigOneOf} The populated <code>AwsPlatformConfigOneOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AwsPlatformConfigOneOf();

            if (data.hasOwnProperty('lambda')) {
                obj['lambda'] = AwsPlatformConfigOneOfLambda.constructFromObject(data['lambda']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AwsPlatformConfigOneOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AwsPlatformConfigOneOf</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AwsPlatformConfigOneOf.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `lambda`
        if (data['lambda']) { // data not null
          AwsPlatformConfigOneOfLambda.validateJSON(data['lambda']);
        }

        return true;
    }


}

AwsPlatformConfigOneOf.RequiredProperties = ["lambda"];

/**
 * @member {module:model/AwsPlatformConfigOneOfLambda} lambda
 */
AwsPlatformConfigOneOf.prototype['lambda'] = undefined;






export default AwsPlatformConfigOneOf;

