/**
 * MultiTool
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationConfig from './ApplicationConfig';

/**
 * The CreateApplicationRequest model module.
 * @module model/CreateApplicationRequest
 * @version 0.1.0
 */
class CreateApplicationRequest {
    /**
     * Constructs a new <code>CreateApplicationRequest</code>.
     * @alias module:model/CreateApplicationRequest
     * @param config {module:model/ApplicationConfig} 
     * @param displayName {String} 
     */
    constructor(config, displayName) { 
        
        CreateApplicationRequest.initialize(this, config, displayName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, config, displayName) { 
        obj['config'] = config;
        obj['display_name'] = displayName;
    }

    /**
     * Constructs a <code>CreateApplicationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateApplicationRequest} obj Optional instance to populate.
     * @return {module:model/CreateApplicationRequest} The populated <code>CreateApplicationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateApplicationRequest();

            if (data.hasOwnProperty('config')) {
                obj['config'] = ApplicationConfig.constructFromObject(data['config']);
            }
            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateApplicationRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateApplicationRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateApplicationRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `config`
        if (data['config']) { // data not null
          ApplicationConfig.validateJSON(data['config']);
        }
        // ensure the json data is a string
        if (data['display_name'] && !(typeof data['display_name'] === 'string' || data['display_name'] instanceof String)) {
            throw new Error("Expected the field `display_name` to be a primitive type in the JSON string but got " + data['display_name']);
        }

        return true;
    }


}

CreateApplicationRequest.RequiredProperties = ["config", "display_name"];

/**
 * @member {module:model/ApplicationConfig} config
 */
CreateApplicationRequest.prototype['config'] = undefined;

/**
 * @member {String} display_name
 */
CreateApplicationRequest.prototype['display_name'] = undefined;






export default CreateApplicationRequest;

