/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateUserFailureOneOfEmailAlreadyRegistered from './CreateUserFailureOneOfEmailAlreadyRegistered';

/**
 * The CreateUserFailureOneOf model module.
 * @module model/CreateUserFailureOneOf
 * @version 0.1.0
 */
class CreateUserFailureOneOf {
    /**
     * Constructs a new <code>CreateUserFailureOneOf</code>.
     * When the email address is already associated with an account.
     * @alias module:model/CreateUserFailureOneOf
     * @param emailAlreadyRegistered {module:model/CreateUserFailureOneOfEmailAlreadyRegistered} 
     */
    constructor(emailAlreadyRegistered) { 
        
        CreateUserFailureOneOf.initialize(this, emailAlreadyRegistered);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, emailAlreadyRegistered) { 
        obj['EmailAlreadyRegistered'] = emailAlreadyRegistered;
    }

    /**
     * Constructs a <code>CreateUserFailureOneOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateUserFailureOneOf} obj Optional instance to populate.
     * @return {module:model/CreateUserFailureOneOf} The populated <code>CreateUserFailureOneOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateUserFailureOneOf();

            if (data.hasOwnProperty('EmailAlreadyRegistered')) {
                obj['EmailAlreadyRegistered'] = CreateUserFailureOneOfEmailAlreadyRegistered.constructFromObject(data['EmailAlreadyRegistered']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateUserFailureOneOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateUserFailureOneOf</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateUserFailureOneOf.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `EmailAlreadyRegistered`
        if (data['EmailAlreadyRegistered']) { // data not null
          CreateUserFailureOneOfEmailAlreadyRegistered.validateJSON(data['EmailAlreadyRegistered']);
        }

        return true;
    }


}

CreateUserFailureOneOf.RequiredProperties = ["EmailAlreadyRegistered"];

/**
 * @member {module:model/CreateUserFailureOneOfEmailAlreadyRegistered} EmailAlreadyRegistered
 */
CreateUserFailureOneOf.prototype['EmailAlreadyRegistered'] = undefined;






export default CreateUserFailureOneOf;

