/**
 * MultiTool
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateWorkspaceSuccess model module.
 * @module model/CreateWorkspaceSuccess
 * @version 0.1.0
 */
class CreateWorkspaceSuccess {
    /**
     * Constructs a new <code>CreateWorkspaceSuccess</code>.
     * @alias module:model/CreateWorkspaceSuccess
     * @param createdAt {Date} 
     * @param displayName {String} 
     * @param id {String} 
     * @param updatedAt {Date} 
     */
    constructor(createdAt, displayName, id, updatedAt) { 
        
        CreateWorkspaceSuccess.initialize(this, createdAt, displayName, id, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, createdAt, displayName, id, updatedAt) { 
        obj['created_at'] = createdAt;
        obj['display_name'] = displayName;
        obj['id'] = id;
        obj['updated_at'] = updatedAt;
    }

    /**
     * Constructs a <code>CreateWorkspaceSuccess</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateWorkspaceSuccess} obj Optional instance to populate.
     * @return {module:model/CreateWorkspaceSuccess} The populated <code>CreateWorkspaceSuccess</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateWorkspaceSuccess();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateWorkspaceSuccess</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateWorkspaceSuccess</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateWorkspaceSuccess.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['display_name'] && !(typeof data['display_name'] === 'string' || data['display_name'] instanceof String)) {
            throw new Error("Expected the field `display_name` to be a primitive type in the JSON string but got " + data['display_name']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}

CreateWorkspaceSuccess.RequiredProperties = ["created_at", "display_name", "id", "updated_at"];

/**
 * @member {Date} created_at
 */
CreateWorkspaceSuccess.prototype['created_at'] = undefined;

/**
 * @member {String} display_name
 */
CreateWorkspaceSuccess.prototype['display_name'] = undefined;

/**
 * @member {String} id
 */
CreateWorkspaceSuccess.prototype['id'] = undefined;

/**
 * @member {Date} updated_at
 */
CreateWorkspaceSuccess.prototype['updated_at'] = undefined;






export default CreateWorkspaceSuccess;

