/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateUserFailureOneOf1 model module.
 * @module model/CreateUserFailureOneOf1
 * @version 0.1.0
 */
class CreateUserFailureOneOf1 {
    /**
     * Constructs a new <code>CreateUserFailureOneOf1</code>.
     * When the user&#39;s email or account name are illegal.
     * @alias module:model/CreateUserFailureOneOf1
     * @param illegalUserDetails {String} When the user's email or account name are illegal.
     */
    constructor(illegalUserDetails) { 
        
        CreateUserFailureOneOf1.initialize(this, illegalUserDetails);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, illegalUserDetails) { 
        obj['IllegalUserDetails'] = illegalUserDetails;
    }

    /**
     * Constructs a <code>CreateUserFailureOneOf1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateUserFailureOneOf1} obj Optional instance to populate.
     * @return {module:model/CreateUserFailureOneOf1} The populated <code>CreateUserFailureOneOf1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateUserFailureOneOf1();

            if (data.hasOwnProperty('IllegalUserDetails')) {
                obj['IllegalUserDetails'] = ApiClient.convertToType(data['IllegalUserDetails'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateUserFailureOneOf1</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateUserFailureOneOf1</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateUserFailureOneOf1.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['IllegalUserDetails'] && !(typeof data['IllegalUserDetails'] === 'string' || data['IllegalUserDetails'] instanceof String)) {
            throw new Error("Expected the field `IllegalUserDetails` to be a primitive type in the JSON string but got " + data['IllegalUserDetails']);
        }

        return true;
    }


}

CreateUserFailureOneOf1.RequiredProperties = ["IllegalUserDetails"];

/**
 * When the user's email or account name are illegal.
 * @member {String} IllegalUserDetails
 */
CreateUserFailureOneOf1.prototype['IllegalUserDetails'] = undefined;






export default CreateUserFailureOneOf1;

