/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateUserSuccess model module.
 * @module model/CreateUserSuccess
 * @version 0.1.0
 */
class CreateUserSuccess {
    /**
     * Constructs a new <code>CreateUserSuccess</code>.
     * Successful user creation response body
     * @alias module:model/CreateUserSuccess
     * @param createdAt {Date} 
     * @param email {String} 
     * @param jwt {String} 
     */
    constructor(createdAt, email, jwt) { 
        
        CreateUserSuccess.initialize(this, createdAt, email, jwt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, createdAt, email, jwt) { 
        obj['created_at'] = createdAt;
        obj['email'] = email;
        obj['jwt'] = jwt;
    }

    /**
     * Constructs a <code>CreateUserSuccess</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateUserSuccess} obj Optional instance to populate.
     * @return {module:model/CreateUserSuccess} The populated <code>CreateUserSuccess</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateUserSuccess();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('jwt')) {
                obj['jwt'] = ApiClient.convertToType(data['jwt'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateUserSuccess</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateUserSuccess</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateUserSuccess.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['jwt'] && !(typeof data['jwt'] === 'string' || data['jwt'] instanceof String)) {
            throw new Error("Expected the field `jwt` to be a primitive type in the JSON string but got " + data['jwt']);
        }

        return true;
    }


}

CreateUserSuccess.RequiredProperties = ["created_at", "email", "jwt"];

/**
 * @member {Date} created_at
 */
CreateUserSuccess.prototype['created_at'] = undefined;

/**
 * @member {String} email
 */
CreateUserSuccess.prototype['email'] = undefined;

/**
 * @member {String} jwt
 */
CreateUserSuccess.prototype['jwt'] = undefined;






export default CreateUserSuccess;

