/**
 * MultiTool
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationSummary from './ApplicationSummary';

/**
 * The CreateApplicationSuccess model module.
 * @module model/CreateApplicationSuccess
 * @version 0.1.0
 */
class CreateApplicationSuccess {
    /**
     * Constructs a new <code>CreateApplicationSuccess</code>.
     * @alias module:model/CreateApplicationSuccess
     * @param application {module:model/ApplicationSummary} 
     */
    constructor(application) { 
        
        CreateApplicationSuccess.initialize(this, application);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, application) { 
        obj['application'] = application;
    }

    /**
     * Constructs a <code>CreateApplicationSuccess</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateApplicationSuccess} obj Optional instance to populate.
     * @return {module:model/CreateApplicationSuccess} The populated <code>CreateApplicationSuccess</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateApplicationSuccess();

            if (data.hasOwnProperty('application')) {
                obj['application'] = ApplicationSummary.constructFromObject(data['application']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateApplicationSuccess</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateApplicationSuccess</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateApplicationSuccess.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `application`
        if (data['application']) { // data not null
          ApplicationSummary.validateJSON(data['application']);
        }

        return true;
    }


}

CreateApplicationSuccess.RequiredProperties = ["application"];

/**
 * @member {module:model/ApplicationSummary} application
 */
CreateApplicationSuccess.prototype['application'] = undefined;






export default CreateApplicationSuccess;

