/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateUserFailureOneOf from './CreateUserFailureOneOf';
import CreateUserFailureOneOf1 from './CreateUserFailureOneOf1';
import CreateUserFailureOneOfEmailAlreadyRegistered from './CreateUserFailureOneOfEmailAlreadyRegistered';

/**
 * The CreateUserFailure model module.
 * @module model/CreateUserFailure
 * @version 0.1.0
 */
class CreateUserFailure {
    /**
     * Constructs a new <code>CreateUserFailure</code>.
     * Failure to create a new users. Corresponds to POST /users/
     * @alias module:model/CreateUserFailure
     * @param {(module:model/CreateUserFailureOneOf|module:model/CreateUserFailureOneOf1|module:model/String)} instance The actual instance to initialize CreateUserFailure.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "CreateUserFailureOneOf") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                CreateUserFailureOneOf.validateJSON(instance); // throw an exception if no match
                // create CreateUserFailureOneOf from JS object
                this.actualInstance = CreateUserFailureOneOf.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into CreateUserFailureOneOf
            errorMessages.push("Failed to construct CreateUserFailureOneOf: " + err)
        }

        // When the user's password is not strong enough.
        try {
            // validate string
            if (!(typeof instance === 'string')) {
                throw new Error("Invalid value. Must be string. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into String
            errorMessages.push("Failed to construct String: " + err)
        }

        // When the server encountered an internal error.
        try {
            // validate string
            if (!(typeof instance === 'string')) {
                throw new Error("Invalid value. Must be string. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into String
            errorMessages.push("Failed to construct String: " + err)
        }

        try {
            if (typeof instance === "CreateUserFailureOneOf1") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                CreateUserFailureOneOf1.validateJSON(instance); // throw an exception if no match
                // create CreateUserFailureOneOf1 from JS object
                this.actualInstance = CreateUserFailureOneOf1.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into CreateUserFailureOneOf1
            errorMessages.push("Failed to construct CreateUserFailureOneOf1: " + err)
        }

        // When the user's password matches their account name or email.
        try {
            // validate string
            if (!(typeof instance === 'string')) {
                throw new Error("Invalid value. Must be string. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into String
            errorMessages.push("Failed to construct String: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `CreateUserFailure` with oneOf schemas CreateUserFailureOneOf, CreateUserFailureOneOf1, String. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `CreateUserFailure` with oneOf schemas CreateUserFailureOneOf, CreateUserFailureOneOf1, String. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>CreateUserFailure</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateUserFailure} obj Optional instance to populate.
     * @return {module:model/CreateUserFailure} The populated <code>CreateUserFailure</code> instance.
     */
    static constructFromObject(data, obj) {
        return new CreateUserFailure(data);
    }

    /**
     * Gets the actual instance, which can be <code>CreateUserFailureOneOf</code>, <code>CreateUserFailureOneOf1</code>, <code>String</code>.
     * @return {(module:model/CreateUserFailureOneOf|module:model/CreateUserFailureOneOf1|module:model/String)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>CreateUserFailureOneOf</code>, <code>CreateUserFailureOneOf1</code>, <code>String</code>.
     * @param {(module:model/CreateUserFailureOneOf|module:model/CreateUserFailureOneOf1|module:model/String)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = CreateUserFailure.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of CreateUserFailure from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/CreateUserFailure} An instance of CreateUserFailure.
     */
    static fromJSON = function(json_string){
        return CreateUserFailure.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/CreateUserFailureOneOfEmailAlreadyRegistered} EmailAlreadyRegistered
 */
CreateUserFailure.prototype['EmailAlreadyRegistered'] = undefined;

/**
 * When the user's email or account name are illegal.
 * @member {Object} IllegalUserDetails
 */
CreateUserFailure.prototype['IllegalUserDetails'] = undefined;


CreateUserFailure.OneOf = ["CreateUserFailureOneOf", "CreateUserFailureOneOf1", "String"];

export default CreateUserFailure;

