/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HeartbeatController200Response model module.
 * @module model/HeartbeatController200Response
 * @version 0.1.0
 */
class HeartbeatController200Response {
    /**
     * Constructs a new <code>HeartbeatController200Response</code>.
     * A Heartbeat response indicates the status of the server. In almost every conceivable circumstance, the response should be a success.
     * @alias module:model/HeartbeatController200Response
     * @param ok {Boolean} 
     */
    constructor(ok) { 
        
        HeartbeatController200Response.initialize(this, ok);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ok) { 
        obj['ok'] = ok;
    }

    /**
     * Constructs a <code>HeartbeatController200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HeartbeatController200Response} obj Optional instance to populate.
     * @return {module:model/HeartbeatController200Response} The populated <code>HeartbeatController200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HeartbeatController200Response();

            if (data.hasOwnProperty('ok')) {
                obj['ok'] = ApiClient.convertToType(data['ok'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HeartbeatController200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HeartbeatController200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of HeartbeatController200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

HeartbeatController200Response.RequiredProperties = ["ok"];

/**
 * @member {Boolean} ok
 */
HeartbeatController200Response.prototype['ok'] = undefined;






export default HeartbeatController200Response;

