/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationSummary from './ApplicationSummary';

/**
 * The ListApplicationsSuccess model module.
 * @module model/ListApplicationsSuccess
 * @version 0.1.0
 */
class ListApplicationsSuccess {
    /**
     * Constructs a new <code>ListApplicationsSuccess</code>.
     * @alias module:model/ListApplicationsSuccess
     * @param applications {Array.<module:model/ApplicationSummary>} 
     */
    constructor(applications) { 
        
        ListApplicationsSuccess.initialize(this, applications);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, applications) { 
        obj['applications'] = applications;
    }

    /**
     * Constructs a <code>ListApplicationsSuccess</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListApplicationsSuccess} obj Optional instance to populate.
     * @return {module:model/ListApplicationsSuccess} The populated <code>ListApplicationsSuccess</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListApplicationsSuccess();

            if (data.hasOwnProperty('applications')) {
                obj['applications'] = ApiClient.convertToType(data['applications'], [ApplicationSummary]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListApplicationsSuccess</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListApplicationsSuccess</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ListApplicationsSuccess.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['applications']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['applications'])) {
                throw new Error("Expected the field `applications` to be an array in the JSON data but got " + data['applications']);
            }
            // validate the optional field `applications` (array)
            for (const item of data['applications']) {
                ApplicationSummary.validateJSON(item);
            };
        }

        return true;
    }


}

ListApplicationsSuccess.RequiredProperties = ["applications"];

/**
 * @member {Array.<module:model/ApplicationSummary>} applications
 */
ListApplicationsSuccess.prototype['applications'] = undefined;






export default ListApplicationsSuccess;

