/**
 * MultiTool
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WorkspaceSummary from './WorkspaceSummary';

/**
 * The ListWorkspaceSuccess model module.
 * @module model/ListWorkspaceSuccess
 * @version 0.1.0
 */
class ListWorkspaceSuccess {
    /**
     * Constructs a new <code>ListWorkspaceSuccess</code>.
     * @alias module:model/ListWorkspaceSuccess
     * @param workspaces {Array.<module:model/WorkspaceSummary>} 
     */
    constructor(workspaces) { 
        
        ListWorkspaceSuccess.initialize(this, workspaces);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, workspaces) { 
        obj['workspaces'] = workspaces;
    }

    /**
     * Constructs a <code>ListWorkspaceSuccess</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListWorkspaceSuccess} obj Optional instance to populate.
     * @return {module:model/ListWorkspaceSuccess} The populated <code>ListWorkspaceSuccess</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListWorkspaceSuccess();

            if (data.hasOwnProperty('workspaces')) {
                obj['workspaces'] = ApiClient.convertToType(data['workspaces'], [WorkspaceSummary]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListWorkspaceSuccess</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListWorkspaceSuccess</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ListWorkspaceSuccess.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['workspaces']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['workspaces'])) {
                throw new Error("Expected the field `workspaces` to be an array in the JSON data but got " + data['workspaces']);
            }
            // validate the optional field `workspaces` (array)
            for (const item of data['workspaces']) {
                WorkspaceSummary.validateJSON(item);
            };
        }

        return true;
    }


}

ListWorkspaceSuccess.RequiredProperties = ["workspaces"];

/**
 * @member {Array.<module:model/WorkspaceSummary>} workspaces
 */
ListWorkspaceSuccess.prototype['workspaces'] = undefined;






export default ListWorkspaceSuccess;

