/**
 * MultiTool
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoginSuccess model module.
 * @module model/LoginSuccess
 * @version 0.1.0
 */
class LoginSuccess {
    /**
     * Constructs a new <code>LoginSuccess</code>.
     * Successful login response payload
     * @alias module:model/LoginSuccess
     * @param email {String} 
     * @param expiresAt {String} 
     * @param jwt {String} 
     */
    constructor(email, expiresAt, jwt) { 
        
        LoginSuccess.initialize(this, email, expiresAt, jwt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, expiresAt, jwt) { 
        obj['email'] = email;
        obj['expires_at'] = expiresAt;
        obj['jwt'] = jwt;
    }

    /**
     * Constructs a <code>LoginSuccess</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoginSuccess} obj Optional instance to populate.
     * @return {module:model/LoginSuccess} The populated <code>LoginSuccess</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginSuccess();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('expires_at')) {
                obj['expires_at'] = ApiClient.convertToType(data['expires_at'], 'String');
            }
            if (data.hasOwnProperty('jwt')) {
                obj['jwt'] = ApiClient.convertToType(data['jwt'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LoginSuccess</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LoginSuccess</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LoginSuccess.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['expires_at'] && !(typeof data['expires_at'] === 'string' || data['expires_at'] instanceof String)) {
            throw new Error("Expected the field `expires_at` to be a primitive type in the JSON string but got " + data['expires_at']);
        }
        // ensure the json data is a string
        if (data['jwt'] && !(typeof data['jwt'] === 'string' || data['jwt'] instanceof String)) {
            throw new Error("Expected the field `jwt` to be a primitive type in the JSON string but got " + data['jwt']);
        }

        return true;
    }


}

LoginSuccess.RequiredProperties = ["email", "expires_at", "jwt"];

/**
 * @member {String} email
 */
LoginSuccess.prototype['email'] = undefined;

/**
 * @member {String} expires_at
 */
LoginSuccess.prototype['expires_at'] = undefined;

/**
 * @member {String} jwt
 */
LoginSuccess.prototype['jwt'] = undefined;






export default LoginSuccess;

