/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AwsConfig from './AwsConfig';
import WebServiceConfigOneOf from './WebServiceConfigOneOf';

/**
 * The WebServiceConfig model module.
 * @module model/WebServiceConfig
 * @version 0.1.0
 */
class WebServiceConfig {
    /**
     * Constructs a new <code>WebServiceConfig</code>.
     * @alias module:model/WebServiceConfig
     * @param {(module:model/WebServiceConfigOneOf)} instance The actual instance to initialize WebServiceConfig.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "WebServiceConfigOneOf") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                WebServiceConfigOneOf.validateJSON(instance); // throw an exception if no match
                // create WebServiceConfigOneOf from JS object
                this.actualInstance = WebServiceConfigOneOf.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into WebServiceConfigOneOf
            errorMessages.push("Failed to construct WebServiceConfigOneOf: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `WebServiceConfig` with oneOf schemas WebServiceConfigOneOf. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `WebServiceConfig` with oneOf schemas WebServiceConfigOneOf. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>WebServiceConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebServiceConfig} obj Optional instance to populate.
     * @return {module:model/WebServiceConfig} The populated <code>WebServiceConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        return new WebServiceConfig(data);
    }

    /**
     * Gets the actual instance, which can be <code>WebServiceConfigOneOf</code>.
     * @return {(module:model/WebServiceConfigOneOf)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>WebServiceConfigOneOf</code>.
     * @param {(module:model/WebServiceConfigOneOf)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = WebServiceConfig.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of WebServiceConfig from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/WebServiceConfig} An instance of WebServiceConfig.
     */
    static fromJSON = function(json_string){
        return WebServiceConfig.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/AwsConfig} aws
 */
WebServiceConfig.prototype['aws'] = undefined;


WebServiceConfig.OneOf = ["WebServiceConfigOneOf"];

export default WebServiceConfig;

