/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AwsConfig from './AwsConfig';

/**
 * The WebServiceConfigOneOf model module.
 * @module model/WebServiceConfigOneOf
 * @version 0.1.0
 */
class WebServiceConfigOneOf {
    /**
     * Constructs a new <code>WebServiceConfigOneOf</code>.
     * @alias module:model/WebServiceConfigOneOf
     * @param aws {module:model/AwsConfig} 
     */
    constructor(aws) { 
        
        WebServiceConfigOneOf.initialize(this, aws);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, aws) { 
        obj['aws'] = aws;
    }

    /**
     * Constructs a <code>WebServiceConfigOneOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebServiceConfigOneOf} obj Optional instance to populate.
     * @return {module:model/WebServiceConfigOneOf} The populated <code>WebServiceConfigOneOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebServiceConfigOneOf();

            if (data.hasOwnProperty('aws')) {
                obj['aws'] = AwsConfig.constructFromObject(data['aws']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebServiceConfigOneOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebServiceConfigOneOf</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WebServiceConfigOneOf.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `aws`
        if (data['aws']) { // data not null
          AwsConfig.validateJSON(data['aws']);
        }

        return true;
    }


}

WebServiceConfigOneOf.RequiredProperties = ["aws"];

/**
 * @member {module:model/AwsConfig} aws
 */
WebServiceConfigOneOf.prototype['aws'] = undefined;






export default WebServiceConfigOneOf;

