/**
 * MultiTool
 * MultiTool
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationSummary from './ApplicationSummary';

/**
 * The WorkspaceDetails model module.
 * @module model/WorkspaceDetails
 * @version 0.1.0
 */
class WorkspaceDetails {
    /**
     * Constructs a new <code>WorkspaceDetails</code>.
     * Details about a particular workspace.
     * @alias module:model/WorkspaceDetails
     * @param applications {Array.<module:model/ApplicationSummary>} 
     * @param createdAt {Date} 
     * @param displayName {String} 
     * @param id {String} 
     * @param updatedAt {Date} 
     */
    constructor(applications, createdAt, displayName, id, updatedAt) { 
        
        WorkspaceDetails.initialize(this, applications, createdAt, displayName, id, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, applications, createdAt, displayName, id, updatedAt) { 
        obj['applications'] = applications;
        obj['created_at'] = createdAt;
        obj['display_name'] = displayName;
        obj['id'] = id;
        obj['updated_at'] = updatedAt;
    }

    /**
     * Constructs a <code>WorkspaceDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkspaceDetails} obj Optional instance to populate.
     * @return {module:model/WorkspaceDetails} The populated <code>WorkspaceDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkspaceDetails();

            if (data.hasOwnProperty('applications')) {
                obj['applications'] = ApiClient.convertToType(data['applications'], [ApplicationSummary]);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WorkspaceDetails</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WorkspaceDetails</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WorkspaceDetails.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['applications']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['applications'])) {
                throw new Error("Expected the field `applications` to be an array in the JSON data but got " + data['applications']);
            }
            // validate the optional field `applications` (array)
            for (const item of data['applications']) {
                ApplicationSummary.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['display_name'] && !(typeof data['display_name'] === 'string' || data['display_name'] instanceof String)) {
            throw new Error("Expected the field `display_name` to be a primitive type in the JSON string but got " + data['display_name']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}

WorkspaceDetails.RequiredProperties = ["applications", "created_at", "display_name", "id", "updated_at"];

/**
 * @member {Array.<module:model/ApplicationSummary>} applications
 */
WorkspaceDetails.prototype['applications'] = undefined;

/**
 * @member {Date} created_at
 */
WorkspaceDetails.prototype['created_at'] = undefined;

/**
 * @member {String} display_name
 */
WorkspaceDetails.prototype['display_name'] = undefined;

/**
 * @member {String} id
 */
WorkspaceDetails.prototype['id'] = undefined;

/**
 * @member {Date} updated_at
 */
WorkspaceDetails.prototype['updated_at'] = undefined;






export default WorkspaceDetails;

